import { Bot, Context, InputFile } from "grammy";
import { pool } from "./db";
import { mainKeyboard, confirmKeyboard } from "./keyboards";
import { convertToGel, refreshRatesIfStale } from "./currency";
import { parseTransactionMessage, isParseError, TransactionType } from "./parser";
import { escapeHtml, PARSE_MODE } from "./format";
import { logger } from "./logger";

type Flow = { type: TransactionType; amount?: number; currency?: "RUB"|"GEL"|"USD"; category?: string|null; note?: string|null; stage: "amount"|"category"|"confirm" };
const flows = new Map<number, Flow>();
const money = (n: unknown) => Number(n ?? 0).toFixed(2);
const monthStart = () => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 1); };
const safe = (label: string, fn: (ctx: Context) => Promise<void>) => async (ctx: Context) => { try { await fn(ctx); } catch (e) { logger.error(`${label}: ${e instanceof Error ? e.message : String(e)}`); await ctx.reply("Не удалось выполнить действие. Попробуй позже.", { reply_markup: mainKeyboard }); } };
async function categories(userId: number, type: TransactionType): Promise<string[]> {
 const r = await pool.query<{name:string}>("SELECT name FROM categories WHERE user_id=$1 AND type=$2 ORDER BY name",[userId,type]);
 return r.rows.map(x=>x.name).slice(0,40);
}
async function showBudget(ctx: Context, userId: number) {
 const from=monthStart(), to=new Date(from.getFullYear(),from.getMonth()+1,1);
 const r=await pool.query(`SELECT b.category,b.limit_gel,COALESCE(SUM(t.amount_gel),0) spent FROM budgets b LEFT JOIN transactions t ON t.user_id=b.user_id AND t.type='expense' AND t.category=b.category AND t.created_at >= $2 AND t.created_at < $3 WHERE b.user_id=$1 AND b.month=$2 GROUP BY b.id ORDER BY b.category`,[userId,from,to]);
 if(!r.rowCount) { await ctx.reply("На этот месяц лимиты не заданы. Пришли: /budget Категория сумма (например: /budget Еда 500)", {reply_markup:mainKeyboard}); return; }
 const lines=r.rows.map((x:any)=>{const spent=Number(x.spent),limit=Number(x.limit_gel);return `${escapeHtml(x.category)}: ${money(spent)} / ${money(limit)} GEL${spent>limit?" ⚠️":""}`;});
 await ctx.reply(`<b>Бюджет за месяц</b>\n${lines.join("\n")}`,{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});
}
export function registerFeatureHandlers(bot: Bot): void {
 bot.command("menu",safe("menu",async ctx=>{flows.delete(ctx.from!.id);await ctx.reply("Главное меню",{reply_markup:mainKeyboard});}));
 bot.hears("🔄 Перезапуск",safe("restart",async ctx=>{const userId=ctx.from?.id;const adminId=Number(process.env.ADMIN_TELEGRAM_ID);if(!userId||!Number.isInteger(adminId)||adminId<=0||userId!==adminId){await ctx.reply("Перезапуск доступен только администратору.",{reply_markup:mainKeyboard});return;}await ctx.reply("Перезапускаю бота. Если он запущен через start.bat, процесс автоматически поднимется снова.");logger.info(`Restart requested by admin ${userId}`);process.exit(75);}));
 bot.command("budget",safe("budget",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const m=/^\/budget\s+(.+?)\s+(\d+(?:[.,]\d{1,2})?)\s*$/.exec(ctx.message?.text??"");if(m){const cat=m[1].trim(),limit=Number(m[2].replace(",","."));if(!cat||limit<=0){await ctx.reply("Формат: /budget Категория сумма");return;}const d=monthStart();await pool.query(`INSERT INTO budgets(user_id,month,category,limit_gel) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,month,category) DO UPDATE SET limit_gel=EXCLUDED.limit_gel`,[uid,d,cat,limit]);await ctx.reply(`Лимит для «${escapeHtml(cat)}»: ${money(limit)} GEL`,{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});return;}await showBudget(ctx,uid);}));
 bot.command("category",safe("category",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const m=/^\/category\s+(expense|income)\s+(.+)$/i.exec(ctx.message?.text??"");if(!m){await ctx.reply("Формат: /category expense Еда или /category income Зарплата");return;}const name=m[2].trim().slice(0,60);await pool.query("INSERT INTO categories(user_id,type,name) VALUES($1,$2,$3) ON CONFLICT DO NOTHING",[uid,m[1].toLowerCase(),name]);await ctx.reply(`Категория добавлена: ${escapeHtml(name)}`,{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});}));
 bot.command("goal",safe("goal",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const m=/^\/goal\s+(.+?)\s+(\d+(?:[.,]\d{1,2})?)\s*$/.exec(ctx.message?.text??"");if(!m){const r=await pool.query("SELECT id,title,saved_gel,target_gel FROM savings_goals WHERE user_id=$1 AND active ORDER BY id",[uid]);await ctx.reply(r.rowCount?r.rows.map((x:any)=>`${x.id}. ${escapeHtml(x.title)} — ${money(x.saved_gel)} / ${money(x.target_gel)} GEL`).join("\n"):"Целей пока нет. Создай: /goal Название сумма",{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});return;}await pool.query("INSERT INTO savings_goals(user_id,title,target_gel) VALUES($1,$2,$3)",[uid,m[1].trim().slice(0,120),Number(m[2].replace(",","."))]);await ctx.reply("Цель накопления создана.",{reply_markup:mainKeyboard});}));
 bot.command("save",safe("save",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const m=/^\/save\s+(\d+)\s+(\d+(?:[.,]\d{1,2})?)\s*$/.exec(ctx.message?.text??"");if(!m){await ctx.reply("Формат: /save ID_цели сумма");return;}const r=await pool.query("UPDATE savings_goals SET saved_gel=saved_gel+$3 WHERE id=$1 AND user_id=$2 AND active RETURNING title,saved_gel,target_gel",[Number(m[1]),uid,Number(m[2].replace(",","."))]);if(!r.rowCount){await ctx.reply("Цель не найдена.");return;}const x=r.rows[0];await ctx.reply(`${escapeHtml(x.title)}: ${money(x.saved_gel)} / ${money(x.target_gel)} GEL`,{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});}));
 bot.command("payment",safe("payment",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const m=/^\/payment\s+(\d{1,2})\s+(\d+(?:[.,]\d{1,2})?)\s+(RUB|GEL|USD)\s+(.+)$/i.exec(ctx.message?.text??"");if(!m){const r=await pool.query("SELECT id,title,amount,currency,due_day FROM recurring_payments WHERE user_id=$1 AND active ORDER BY due_day",[uid]);await ctx.reply(r.rowCount?r.rows.map((x:any)=>`${x.id}. ${escapeHtml(x.title)} — ${x.amount} ${x.currency}, день ${x.due_day}`).join("\n"):"Платежей пока нет. Создание: /payment день сумма валюта название",{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});return;}await pool.query("INSERT INTO recurring_payments(user_id,due_day,amount,currency,title) VALUES($1,$2,$3,$4,$5)",[uid,Number(m[1]),Number(m[2].replace(",",".")),m[3].toUpperCase(),m[4].trim().slice(0,120)]);await ctx.reply("Регулярный платёж добавлен.",{reply_markup:mainKeyboard});}));
 bot.command("payments",safe("payments",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const r=await pool.query("SELECT id,title,amount,currency,due_day FROM recurring_payments WHERE user_id=$1 AND active ORDER BY due_day",[uid]);await ctx.reply(r.rowCount?r.rows.map((x:any)=>`${x.id}. ${escapeHtml(x.title)} — ${x.amount} ${x.currency}, день ${x.due_day}`).join("\n"):"Регулярных платежей нет.",{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});}));
 bot.command("stats",safe("stats",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const r=await pool.query(`SELECT category,COALESCE(SUM(amount_gel),0) total FROM transactions WHERE user_id=$1 AND type='expense' AND created_at >= $2 AND created_at < $3 GROUP BY category ORDER BY total DESC LIMIT 10`,[uid,monthStart(),new Date(new Date().getFullYear(),new Date().getMonth()+1,1)]);await ctx.reply(r.rowCount?`<b>Расходы по категориям за месяц</b>\n${r.rows.map((x:any)=>`${escapeHtml(x.category??"Без категории")}: ${money(x.total)} GEL`).join("\n")}`:"За этот месяц расходов нет.",{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});}));
 bot.command("export",safe("export",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const r=await pool.query("SELECT created_at,type,amount,currency,category,note,amount_gel FROM transactions WHERE user_id=$1 ORDER BY created_at DESC LIMIT 5000",[uid]);const q=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;const csv=["date,type,amount,currency,category,note,amount_gel",...r.rows.map((x:any)=>[x.created_at.toISOString(),x.type,x.amount,x.currency,x.category,x.note,x.amount_gel].map(q).join(","))].join("\r\n");await ctx.replyWithDocument(new InputFile(Buffer.from("\uFEFF"+csv,"utf8"),"transactions.csv"),{caption:"Экспорт последних 5000 операций (CSV)"});}));
 bot.command("deletepayment",safe("deletepayment",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const id=Number((ctx.message?.text??"").split(/\s+/)[1]);if(!Number.isInteger(id)||id<1){await ctx.reply("Формат: /deletepayment ID");return;}const r=await pool.query("UPDATE recurring_payments SET active=FALSE WHERE id=$1 AND user_id=$2 RETURNING id",[id,uid]);await ctx.reply(r.rowCount?"Платёж отключён.":"Платёж не найден.",{reply_markup:mainKeyboard});}));
 bot.command("deletegoal",safe("deletegoal",async ctx=>{const uid=ctx.from?.id;if(!uid)return;const id=Number((ctx.message?.text??"").split(/\s+/)[1]);const r=await pool.query("UPDATE savings_goals SET active=FALSE WHERE id=$1 AND user_id=$2 RETURNING id",[id,uid]);await ctx.reply(r.rowCount?"Цель закрыта.":"Цель не найдена.",{reply_markup:mainKeyboard});}));
 bot.on("message:text",safe("menu/text",async ctx=>{const uid=ctx.from?.id;const message=ctx.message;if(!uid||!message||!("text" in message)||typeof message.text!=="string")return;const text=message.text.trim();if(text.startsWith("/"))return;
  if(text==="🔄 Перезапуск"){return;}
  if(text==="❌ Отмена"){flows.delete(uid);await ctx.reply("Действие отменено.",{reply_markup:mainKeyboard});return;}
  if(text==="➖ Расход"||text==="➕ Доход"){const type=text.startsWith("➖")?"expense":"income";flows.set(uid,{type,stage:"amount"});await ctx.reply(`Введи сумму ${type==="expense"?"расхода":"дохода"}, например: 25 GEL Еда обед\nМожно и в старом формате: -25 gel еда обед`,{reply_markup:mainKeyboard});return;}
  if(text==="📊 Бюджет"){await showBudget(ctx,uid);return;}
  if(text==="🧾 История"){const r=await pool.query("SELECT * FROM transactions WHERE user_id=$1 ORDER BY created_at DESC,id DESC LIMIT 10",[uid]);await ctx.reply(r.rowCount?r.rows.map((x:any)=>`${x.type==="expense"?"−":"+"}${x.amount} ${x.currency} ${escapeHtml(x.category??"")} ${escapeHtml(x.note??"")}`).join("\n"):"Операций пока нет.",{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});return;}
  if(text==="🔁 Платежи"){const r=await pool.query("SELECT id,title,amount,currency,due_day FROM recurring_payments WHERE user_id=$1 AND active ORDER BY due_day",[uid]);await ctx.reply((r.rowCount?r.rows.map((x:any)=>`${x.id}. ${escapeHtml(x.title)} — ${x.amount} ${x.currency}, день ${x.due_day}`).join("\n"):"Регулярных платежей нет.")+"\n\nДобавить: /payment день сумма валюта название",{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});return;}
  if(text==="🎯 Накопления"){const r=await pool.query("SELECT id,title,saved_gel,target_gel FROM savings_goals WHERE user_id=$1 AND active ORDER BY id",[uid]);await ctx.reply((r.rowCount?r.rows.map((x:any)=>`${x.id}. ${escapeHtml(x.title)} — ${money(x.saved_gel)} / ${money(x.target_gel)} GEL`).join("\n"):"Целей пока нет.")+"\n\nСоздать: /goal Название сумма\nПополнить: /save ID сумма",{parse_mode:PARSE_MODE,reply_markup:mainKeyboard});return;}
  if(text==="📈 Статистика"){await ctx.api.sendMessage(ctx.chat!.id,"Команда /stats покажет расходы по категориям. /export — выгрузка CSV.",{reply_markup:mainKeyboard});return;}
  if(text==="⚙️ Настройки"){await ctx.reply("Настройки: валюта по умолчанию GEL. Доступные валюты: GEL, RUB, USD.\nКоманды: /category, /budget, /payment, /goal, /export",{reply_markup:mainKeyboard});return;}
  const flow=flows.get(uid);if(flow){const parsed=parseTransactionMessage(text);if(isParseError(parsed)){await ctx.reply(parsed.error);return;}if(parsed.type!==flow.type){await ctx.reply(`Для этого шага нужен ${flow.type==="expense"?"расход (минус)":"доход (плюс)"}.`);return;}flow.amount=parsed.amount;flow.currency=parsed.currency;flow.category=parsed.category;flow.note=parsed.note;flow.stage="confirm";await ctx.reply(`Проверь операцию:\n${flow.type==="expense"?"Расход":"Доход"}: ${flow.amount} ${flow.currency}\nКатегория: ${flow.category??"—"}\nКомментарий: ${flow.note??"—"}`,{reply_markup:confirmKeyboard});return;}
  // Keep the existing one-line transaction parser as a fallback.
  const parsed=parseTransactionMessage(text);if(isParseError(parsed)){await ctx.reply(parsed.error,{reply_markup:mainKeyboard});return;}await refreshRatesIfStale();const gel=convertToGel(parsed.amount,parsed.currency);await pool.query("INSERT INTO transactions(user_id,type,amount,currency,amount_gel,category,note) VALUES($1,$2,$3,$4,$5,$6,$7)",[uid,parsed.type,parsed.amount,parsed.currency,gel,parsed.category,parsed.note]);await ctx.reply("Операция записана.",{reply_markup:mainKeyboard});
 }));
 bot.callbackQuery(/^flow:(save|cancel)$/,safe("flow callback",async ctx=>{const uid=ctx.from?.id;const match=ctx.match;if(!uid||!match){await ctx.answerCallbackQuery({text:"Не удалось определить действие",show_alert:true});return;}const action=match[1];const flow=flows.get(uid);if(action==="cancel"){flows.delete(uid);await ctx.answerCallbackQuery({text:"Отменено"});await ctx.editMessageText("Действие отменено.").catch(()=>{});return;}if(!flow?.amount||!flow.currency){await ctx.answerCallbackQuery({text:"Нет операции для сохранения",show_alert:true});return;}await refreshRatesIfStale();const gel=convertToGel(flow.amount,flow.currency);await pool.query("INSERT INTO transactions(user_id,type,amount,currency,amount_gel,category,note) VALUES($1,$2,$3,$4,$5,$6,$7)",[uid,flow.type,flow.amount,flow.currency,gel,flow.category??null,flow.note??null]);flows.delete(uid);await ctx.answerCallbackQuery({text:"Сохранено"});await ctx.editMessageText("Операция записана.").catch(()=>{});}));
}
